- hosts: web
  gather_facts: true
  remote_user: ubuntu
  vars:
    files:
      - only
      - for
      - illustration
  tasks:
  - name: Printing all the environment variables in Ansible
    debug:
      msg: "{{ ansible_env }}"

  - name: Create remote directories
    file:
      path: "{{item}}"
      state: directory
      mode: 0755
      owner: ubuntu
      group: ubuntu
    with_items:
      - '/home/ubuntu/init'
      - '/home/ubuntu/.vim'
      - '/home/ubuntu/init/dotfiles'

  - name: Sync Init directories
    synchronize:
      src: "{{ lookup('env', 'HOME') }}/init/dotfiles/"
      dest: /home/ubuntu/init/dotfiles/
      delete: yes
      recursive: yes
      rsync_opts:
        - "--no-motd"
        - "--exclude=.git"

  - name: Sync vim directories
    synchronize:
      src: "{{ lookup('env', 'HOME') }}/.vim/"
      dest: /home/ubuntu/.vim/
      delete: yes
      recursive: yes
      rsync_opts:
        - "--no-motd"
        - "--exclude=.git"

  - name: Copy bashrc customization
    copy:
      src: "{{ lookup('env', 'HOME') }}/init/dotfiles/.bashrc_custom"
      dest: /home/ubuntu/.bashrc_custom
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Change ownership
    shell:
        cmd: "chown -R ubuntu:ubuntu /home/ubuntu/init"

  - name: Change ownership
    shell:
        cmd: "chown -R ubuntu:ubuntu /home/ubuntu/.vim"

  - name: Create links
    environment:
        EMBARKK_HOME: /embarkk
    shell:
      cmd: "/home/ubuntu/init/dotfiles/create_links.sh"
      chdir: /home/ubuntu/init/dotfiles
